### ISSUE TITLE
工程里的myapplication怎么编译成jiagu.zip

### ISSUE THREAD

**Issue by smalljames** [godlikewangjun/dexknife-wj#3]

**Comment by godlikewangjun** [comment]
我看了下是加密 dex之后有点大 后面优化算法。 说明里面有 apktool 反编译 apk 提取文件压缩成zip

**Comment by smalljames** [comment]
我用myapplication来编译出来结果没有libapktoolplus_jiagu.so，但你编好的jiagu.zip中有这个libapktoolplus_jiagu.so，貌似对不上，myapplication工程是最新的吗？

**Comment by godlikewangjun** [comment]
![image](https://user-images.githubusercontent.com/7495222/27415719-240e7a3c-573b-11e7-9707-14885d64db9d.png)
jni编出来就是那个名称

**Comment by smalljames** [comment]
好的，谢谢了

**Comment by smalljames** [comment]
用工程myapplication，按照apktool 反编译 apk 提取文件压缩成zip，自已生成的jiagu.zip，大小有45K，libapktoolplus_jiagu.so也有编译在里面了，用来加固，应用启动不了，用你自带的jiagu.zip(47K)就可以正常启动。报错如下：
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.agg.next-1/base.apk"],nativeLibraryDirectories=[/data/app/com.agg.next-1/lib/arm, /data/app/com.agg.next-1/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]] couldn't find "libapktoolplus_jiagu.so"
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:379)
                                                       at java.lang.System.loadLibrary(System.java:1086)
                                                       at com.qianfandu.utils.ApkToolPlus.a(SourceFile:12)
                                                       at com.qianfandu.ProxyApplication.attachBaseContext(SourceFile:32)
                                                       at android.app.Application.attach(Application.java:187)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:998)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:614)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4759)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:165)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:150)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by smalljames** [comment]
OK了，是我自己搞了乌龙，自己搞的加固也能跑得起来了，再次感谢

**Comment by godlikewangjun** [comment]
好的 没问题就好

**Comment by smalljames** [comment]
1.1.1版本有更好的方法生成
