### ISSUE TITLE
能否支持用cmd里输入java -jar dexknife-wj-1.1.1.jar来运行UpdateJiaGu

### ISSUE THREAD

**Issue by smalljames** [godlikewangjun/dexknife-wj#5]
运行时报这样的错：
D:\AppSign>java -jar dexknife-wj-1.1.1.jar
Exception in thread "main" java.lang.NoClassDefFoundError: brut/androlib/Androli
bException
        at UpdateJiaGu.main(UpdateJiaGu.java:85)
Caused by: java.lang.ClassNotFoundException: brut.androlib.AndrolibException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

提示错误行定在JiaGu.ISSHELL找不到

**Comment by godlikewangjun** [comment]
暂时不支持命令。。后面我看弄成task 或者命令，现在是java运行 配置好参数你运行java就可以了
